import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Eventos Smartie ',
  description: 'Generated by create next app',
}

import "primereact/resources/themes/lara-dark-blue/theme.css";
import "tailwindcss/tailwind.css";
import "primereact/resources/primereact.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        {children}</body>
    </html>
  )
}
